# Generated by Django 2.1.4 on 2019-01-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20190105_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='secreteriat',
            name='uni',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apps.University'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='uni',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apps.University'),
            preserve_default=False,
        ),
    ]
